### ISSUE TITLE
Crash on loading of maps!

### ISSUE THREAD

**Issue by Kratom55** [baarsik/Tauros-v2#1]
I can't use this as everytime I launch the cheat it crashes. :(

**Comment by baarsik** [comment]
Issue is confirmed. Please provide additional info including your VC Redist packages installed, OS version, Visual Studio version and confirm that you are using last available version of hack.

**Comment by Kratom55** [comment]
Toolset v140, Windows 10, VS 2015, am using the latest version.

**Comment by Kratom55** [comment]
Update, upgraded to VS 2017. Changed Toolset to 141, and used multiple injectors still the same issue as of now!

**Comment by younasiqw** [comment]
Crash on loading of maps!

**Comment by younasiqw** [comment]
So sad

**Comment by younasiqw** [comment]
Tauros crash fixed?  help me ~~~

**Comment by baarsik** [comment]
Fixed with the latest update
